server:
  port: 8903
  servlet:
    context-path: /
spring:
  application:
    name: lab-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.65:3306/demo?charset=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.ywkd.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true    